
checkout_all:
	-cd ../ && git submodule update --init bsg_ac_black_parrot_dual_core_v0/cad/synth
	cd ../ && git submodule update --init bsg_ac_black_parrot_dual_core_v0/imports/basejump_stl
	cd ../ && git submodule update --init bsg_ac_black_parrot_dual_core_v0/imports/board
	cd ../ && git submodule update --init bsg_ac_black_parrot_dual_core_v0/imports/bsg_designs
	cd ../ && git submodule update --init bsg_ac_black_parrot_dual_core_v0/imports/bsg_packaging
	cd ../ && git submodule update --init bsg_ac_black_parrot_dual_core_v0/imports/pre-alpha-release

